version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      -  27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  zulu-frontend:
    image: zulu-frontend
    restart: always
    ports:
      - 8085:80
    build:
      context: ./frontend/zulu
      dockerfile: Dockerfile
  zulu-backend:
    image: zulu-backend
    restart: always
    ports:
     - 8086:8342
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - ENV_FOR_DYNACONF=compose

